version: 2

project_name: schnappit

before:
  hooks:
    - go mod tidy

builds:
  - id: schnappit
    main: ./cmd/schnappit
    binary: schnappit
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
    # macOS-specific build settings
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=clang
          - CXX=clang++
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++

# Create universal binary for macOS
universal_binaries:
  - id: schnappit-universal
    ids:
      - schnappit
    replace: true
    name_template: schnappit

archives:
  - id: default
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: owenrumney
    name: schnappit
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
