version: 2

project_name: schnappit

before:
  hooks:
    - go mod tidy

builds:
  - id: schnappit
    main: ./cmd/schnappit
    binary: schnappit
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
      - MACOSX_DEPLOYMENT_TARGET=14.0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: owenrumney
    name: schnappit
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

homebrew_casks:
  - name: schnappit
    homepage: https://github.com/owenrumney/schnappit
    description: A macOS screenshot utility
    binaries:
      - schnappit
    hooks:
      post:
        install: |
          # Remove quarantine attribute to avoid Gatekeeper issues
          system_command "/usr/bin/xattr",
                         args: ["-cr", "#{appdir}/Schnappit.app"],
                         sudo: false
    repository:
      owner: owenrumney
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"